### ISSUE TITLE
[Safari] err.stack is empty 

### ISSUE THREAD

**Issue by moszeed** [yoshuawuyts/object-change-callsite#2]
I´m cross-browser testing my current choo app,
with choo-devtools enabled, which is using this plugin.

Works every, except in Safari (running Version 11.0 (13604.1.38.1.6) within an VM),
there i get the following Error:

> TypeError: undefined is not an object (evaluating 'arr[0].replace')

which is triggerd here: https://github.com/yoshuawuyts/object-change-callsite/blob/master/index.js#L33

after some googling around i found that some hints that safari, has some problems with:
> err.stack

which is used in following lines:
https://github.com/yoshuawuyts/object-change-callsite/blob/master/index.js#L12
https://github.com/yoshuawuyts/object-change-callsite/blob/master/index.js#L19

i don't know exactly how to fix, maybe switch if undefined to "err.message" ...

**Comment by toddself** [comment]
Ran into this with choo-devtools and iOS this morning trying to debug another issue.  I'm going to make a PR to ix the `strip` function so it just works on safari but will be ugly

**Comment by yoshuawuyts** [comment]
Fixed in `v1.0.5` :tada:
